settings:
  # Time to solve one round (in seconds)
  time-per-round: 10
  # Number of kicks before ban
  max-kicks-before-ban: 3
  # Ban duration in minutes
  ban-time-minutes: 5
  # How many days player won't see captcha after passing (IP immunity)
  immunity-days: 3

messages:
  prefix: "&8[&bqAnti&fBot&8] "

  kick-reason: "&cYou failed the bot verification!\n&7Try again."
  ban-reason: "&cYour IP is banned for 5 minutes for failing verification."
  title-header: "&8Find: "
  success: "&aYou successfully passed verification!"
  timer-expired: "&cTime's up! You didn't click in time."
  reload: "&aConfig reloaded."

  player-not-found: "&cPlayer not found."
  already-verified: "&cThis player already passed verification or is currently verifying."
  forced-pass: "&aPlayer %player% was forced to pass verification."
  forced-start: "&aVerification started for player %player%."
  unban-success: "&aIP %ip% has been unbanned."
  unban-fail: "&cIP %ip% was not found in ban list."
  bypass: "&aYou have permission to bypass verification."

# Item list (Material 1.16.5: Name for GUI)
# Font: Small Caps + Leet (readable for humans, hard for OCR)
items:
  STONE: "ѕᴛᴏɴᴇ"
  GRASS_BLOCK: "ɢʀᴀѕѕ 6ʟᴏᴄᴋ"
  DIRT: "ᴅɪʀᴛ"
  COBBLESTONE: "ᴄᴏ66ʟᴇѕᴛᴏɴᴇ"
  OAK_PLANKS: "ᴏᴀᴋ ᴘʟᴀɴᴋѕ"
  BEDROCK: "6ᴇᴅʀᴏᴄᴋ"
  SAND: "ѕᴀɴᴅ"
  GRAVEL: "ɢʀᴀᴠᴇʟ"
  GOLD_ORE: "ɢᴏʟᴅ ᴏʀᴇ"
  IRON_ORE: "ɪʀᴏɴ ᴏʀᴇ"
  COAL_ORE: "ᴄᴏᴀʟ ᴏʀᴇ"
  OAK_LOG: "ᴏᴀᴋ ʟᴏɢ"
  STRIPPED_OAK_LOG: "ѕᴛʀɪᴘᴘᴇᴅ ᴏᴀᴋ ʟᴏɢ"
  SPONGE: "ѕᴘᴏɴɢᴇ"
  GLASS: "ɢʟᴀѕѕ"
  LAPIS_ORE: "ʟᴀᴘɪѕ ᴏʀᴇ"
  SANDSTONE: "ѕᴀɴᴅѕᴛᴏɴᴇ"
  WOOL: "ᴡᴏᴏʟ"
  GOLD_BLOCK: "ɢᴏʟᴅ 6ʟᴏᴄᴋ"
  IRON_BLOCK: "ɪʀᴏɴ 6ʟᴏᴄᴋ"
  BRICKS: "6ʀɪᴄᴋѕ"
  TNT: "ᴛɴᴛ"
  BOOKSHELF: "6ᴏᴏᴋѕʜᴇʟғ"
  MOSSY_COBBLESTONE: "ᴍᴏѕѕʏ"
  OBSIDIAN: "ᴏ6ѕɪᴅɪᴀɴ"
  TORCH: "ᴛᴏʀᴄʜ"
  CHEST: "ᴄʜᴇѕᴛ"
  DIAMOND_ORE: "ᴅɪᴀᴍᴏɴᴅ ᴏʀᴇ"
  CRAFTING_TABLE: "ᴄʀᴀғᴛɪɴɢ ᴛᴀ6ʟᴇ"
  FURNACE: "ғᴜʀɴᴀᴄᴇ"
  LADDER: "ʟᴀᴅᴅᴇʀ"
  SNOW: "ѕɴᴏᴡ"
  ICE: "ɪᴄᴇ"
  CACTUS: "ᴄᴀᴄᴛᴜѕ"
  CLAY: "ᴄʟᴀʏ"
  PUMPKIN: "ᴘᴜᴍᴘᴋɪɴ"
  NETHER_RACK: "ɴᴇᴛʜᴇʀ ʀᴀᴄᴋ"
  SOUL_SAND: "ѕᴏᴜʟ ѕᴀɴᴅ"
  GLOWSTONE: "ɢʟᴏᴡѕᴛᴏɴᴇ"
  MELON: "ᴍᴇʟᴏɴ"
  MYCELIUM: "ᴍʏᴄᴇʟɪᴜᴍ"
  EMERALD_ORE: "ᴇᴍᴇʀᴀʟᴅ ᴏʀᴇ"
  BEACON: "6ᴇᴀᴄᴏɴ"
  ANVIL: "ᴀɴᴠɪʟ"
  SLIME_BLOCK: "6ʟᴏᴄᴋ ᴏғ ѕʟɪᴍᴇ"
  BARRIER: "6ᴀʀʀɪᴇʀ"
  IRON_TRAPDOOR: "ɪʀᴏɴ ᴛʀᴀᴘᴅᴏᴏʀ"
  HAY_BLOCK: "ʜᴀʏ 6ʟᴏᴄᴋ"
  COAL_BLOCK: "ᴄᴏᴀʟ 6ʟᴏᴄᴋ"
  PACKED_ICE: "ᴘᴀᴄᴋᴇᴅ ɪᴄᴇ"
